name: Build / CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Give actions-user a permission to commit (for coverage.svg)
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    # Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Build check to ensure code compiles
    - name: Build
      run: go build ./...

    # Run unit tests (excluding examples/)
    - name: Run unit tests only (excluding examples/)
      run: go list ./... | grep -v /examples | xargs go test -v -short

    - name: Check secret length
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Length of AWS key: ${#AWS_REGION}"

    # Run all tests (unit + integration) and generate coverage (excluding examples/)
    - name: Run all tests (unit + integration) with coverage (excluding examples/)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        go list ./... | grep -v /examples | xargs go test -v -coverprofile=coverage.out

    # Generate coverage badge
    - name: Generate coverage badge
      run: |
        # Get total coverage %
            COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
        # Decide color
            COLOR=brightgreen
            if (( $(echo "$COVERAGE < 80" | bc -l) )); then COLOR=red; fi
        # Generate badge using Shields.io
            curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}" > coverage.svg

    # Commit coverage badge 
    - name: Commit coverage badge
      run: |
        # Configure Git for GitHub Actions
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        # Add the coverage badge
        git add coverage.svg
        
        # Only commit if there are changes
        if ! git diff --cached --quiet; then
            git commit -m "Changes detected, update coverage badge"
            git push
        else
            echo "No changes to commit"
        fi

    # Lint the code for style and quality
    - name: Lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run